org: groros
app: pay-per-lead-project
service: lead-ingestion-notification-workflow

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-east-1
  profile: serverless-admin
  timeout: 10
  memorySize: 128 
  iam:
    role:
      statements:
        - Effect: Allow
          Action: 
            - sqs:SendMessage
            - sqs:GetQueueUrl
            - sqs:ListQueues
          Resource: "arn:aws:sqs:us-east-1:906360379090:send-new-lead-notification-dev-jobs"
        - Effect: Allow
          Action:
            - sqs:SendMessage
            - sqs:GetQueueUrl
            - sqs:ListQueues
          Resource: "arn:aws:sqs:us-east-1:906360379090:send-new-lead-notification-email-dev-jobs"
  environment:
    SQS_SMS_QUEUE_URL: https://sqs.us-east-1.amazonaws.com/906360379090/send-new-lead-notification-dev-jobs
    SQS_EMAIL_QUEUE_URL: https://sqs.us-east-1.amazonaws.com/906360379090/send-new-lead-notification-email-dev-jobs
    REGION_NAME: ${self:provider.region}
    STAGE: ${provider.stage}

plugins:
  - serverless-python-requirements
  - serverless-step-functions

functions:
  add_lead_dynamo:
    handler: src/add_lead_to_dynamo.add_lead_to_dynamo
  create_lead_product:
    handler: src/create_lead_product_stripe.create_lead_product_stripe
    environment:
      STRIPE_TEST_API_KEY: ${param:STRIPE_TEST_API_KEY}
      STRIPE_API_KEY: ${param:STRIPE_API_KEY}
  create_lead_price:
    handler: src/create_lead_price_stripe.create_lead_price_stripe
    environment:
      STRIPE_TEST_API_KEY: ${param:STRIPE_TEST_API_KEY}
      STRIPE_API_KEY: ${param:STRIPE_API_KEY}
  create_lead_pl:
    handler: src/create_payment_link.create_payment_link
    environment:
      STRIPE_TEST_API_KEY: ${param:STRIPE_TEST_API_KEY}
      STRIPE_API_KEY: ${param:STRIPE_API_KEY}
  get_full_address:
    handler: src/get_full_address.get_full_address
    environment:
      GOOGLE_API_KEY: ${param:GOOGLE_API_KEY}
  lead_noti_spawner:
    handler: src/lead_notification_spawner.lead_notification_spawner

stepFunctions:
  stateMachines:
    newLeadIngestion:
      name: new-lead-ingestion-workflow
      events:
        - http:
            path: ingest_lead
            method: POST
      definition: ${file(src/workflow.asl.yaml)}