org: groros
app: pay-per-lead-project
service: lead-ingestion-notification-workflow

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-east-1
  profile: serverless-admin
  timeout: 10
  memorySize: 128 
  environment:
    REGION_NAME: ${self:provider.region}

plugins:
  - serverless-python-requirements
  - serverless-step-functions

functions:
  create_lead_product_stripe:
    handler: src/create_lead_product_stripe.create_lead_product_stripe
    # environment:
    #   STRIPE_TEST_API_KEY: ${param:STRIPE_TEST_API_KEY}
    #   STRIPE_API_KEY: ${param:STRIPE_API_KEY}
